---
- name: Create sssd config directory
  file:
    state: directory
    path: "{{ sssd_config_file | dirname }}"

- name: Configure sssd
  template:
    src: sssd.conf
    dest: "{{ sssd_config_file }}"
    owner: root
    group: root
    mode: u=rw,g=,o=
  notify: restart sssd

- name: Ensure disabled sssd activatable responders are masked
  ansible.builtin.service:
    name: sssd-{{ item }}
    masked: yes
  loop: "{{ sssd_disabled_activatable_responders |
            product(['socket', 'service']) |
            map('join', '.') }}"
  loop_control:
    label: "sssd-{{ item }}"
  when: sssd_enable_activatable_responders

- name: Ensure enabled sssd activatable responders are unmasked
  ansible.builtin.service:
    name: sssd-{{ item }}
    masked: no
  loop: "{{ sssd_config.sssd.services |
            difference(sssd_disabled_activatable_responders) |
            product(['socket', 'service']) |
            map('join', '.') }}"
  loop_control:
    label: "sssd-{{ item }}"
  when:
    - sssd_config.sssd.services is defined
    - sssd_enable_activatable_responders

- name: Install sssd packages
  apt:
    name: "{{ sssd_packages }}"
    install_recommends: no
    state: present
  notify: restart systemd-logind

- name: Enable automatic home directory creation
  lineinfile:
    path: /etc/pam.d/common-session
    regexp: 'pam_mkhomedir\.so'
    line: "session required pam_mkhomedir.so skel=/etc/skel/ umask=0022"
    state: present
  when: sssd_mkhomedir

- name: Disable automatic home directory creation
  lineinfile:
    path: /etc/pam.d/common-session
    regexp: 'pam_mkhomedir\.so'
    state: absent
  when: not sssd_mkhomedir

- name: Ensure disabled sssd activatable responders are stopped
  ansible.builtin.service:
    name: sssd-{{ item }}
    state: stopped
  loop: "{{ sssd_disabled_activatable_responders |
            product(['socket', 'service']) |
            map('join', '.') }}"
  loop_control:
    label: "sssd-{{ item }}"
  when: sssd_enable_activatable_responders

- name: Ensure enabled sssd activatable responder sockets are enabled
  ansible.builtin.service:
    name: sssd-{{ item }}.socket
    enabled: yes
  loop: "{{ sssd_config.sssd.services | difference(sssd_disabled_activatable_responders) }}"
  loop_control:
    label: "sssd-{{ item }}.socket"
  when:
    - sssd_config.sssd.services is defined
    - sssd_enable_activatable_responders

- name: Ensure sssd service is started and enabled
  ansible.builtin.service:
    name: sssd
    state: started
    enabled: yes
