---
- name: Create sssd config directory
  file:
    state: directory
    path: "{{ sssd_config_file | dirname }}"

- name: Configure sssd
  template:
    src: sssd.conf
    dest: "{{ sssd_config_file }}"
    owner: root
    group: root
    mode: u=rw,g=,o=
  notify: restart sssd

- name: Install sssd packages
  apt:
    name: "{{ sssd_packages }}"
    update_cache: yes
    state: present
  notify: restart systemd-logind

- name: Enable automatic home directory creation
  lineinfile:
    path: /etc/pam.d/common-session
    regexp: 'pam_mkhomedir\.so'
    line: "session required pam_mkhomedir.so skel=/etc/skel/ umask=0022"
    state: present
  when: sssd_mkhomedir

- name: Disable automatic home directory creation
  lineinfile:
    path: /etc/pam.d/common-session
    regexp: 'pam_mkhomedir\.so'
    state: absent
  when: not sssd_mkhomedir

- name: Ensure sssd service is started and enabled
  service:
    name: sssd
    state: started
    enabled: yes
