---
- name: Create sssd config directory
  ansible.builtin.file:
    state: directory
    path: "{{ sssd_config_file | dirname }}"
    mode: u=rwx,g=x,o=x

- name: Configure sssd
  ansible.builtin.template:
    src: sssd.conf
    dest: "{{ sssd_config_file }}"
    owner: root
    group: root
    mode: u=rw,g=,o=
  notify: restart sssd

- name: Mask disabled sssd activatable responders
  ansible.builtin.systemd:
    name: sssd-{{ item }}
    masked: yes
  loop: "{{ sssd_disabled_activatable_responder_systemd_units }}"
  loop_control:
    label: "sssd-{{ item }}"
  when: sssd_manage_activatable_responders

- name: Unmask enabled sssd activatable responders
  ansible.builtin.systemd:
    name: sssd-{{ item }}
    masked: no
  loop: "{{ sssd_enabled_activatable_responder_systemd_units }}"
  loop_control:
    label: "sssd-{{ item }}"
  when: sssd_manage_activatable_responders

- name: Install sssd packages
  ansible.builtin.apt:
    name: "{{ sssd_packages }}"
    install_recommends: no
    state: present
  notify: restart systemd-logind

- name: Enable automatic home directory creation
  ansible.builtin.lineinfile:
    path: /etc/pam.d/common-session
    regexp: 'pam_mkhomedir\.so'
    line: "session required pam_mkhomedir.so skel=/etc/skel/ umask=0022"
    state: present
  when: sssd_mkhomedir

- name: Disable automatic home directory creation
  ansible.builtin.lineinfile:
    path: /etc/pam.d/common-session
    regexp: 'pam_mkhomedir\.so'
    state: absent
  when: not sssd_mkhomedir

- name: Enable configured sssd activatable responder sockets
  ansible.builtin.service:
    name: sssd-{{ item }}
    enabled: yes
  loop: "{{ sssd_enabled_activatable_responder_systemd_sockets }}"
  loop_control:
    label: "sssd-{{ item }}"
  when: sssd_manage_activatable_responders

- name: Enable sssd service
  ansible.builtin.service:
    name: sssd
    enabled: yes
  notify: restart sssd
