---
- name: Restart sssd
  ansible.builtin.service:
    name: sssd
    state: restarted
  listen: restart sssd

- name: Stop disabled sssd activatable responders
  ansible.builtin.service:
    name: sssd-{{ item }}
    state: stopped
  loop: "{{ sssd_disabled_activatable_responders |
            product(['socket', 'service']) |
            map('join', '.') }}"
  loop_control:
    label: "sssd-{{ item }}"
  when: sssd_enable_activatable_responders
  register: _sssd_activatable_responders_disabled
  listen: restart sssd

- name: Restart sssd to acquire locks held by activatable responders
  ansible.builtin.service:
    name: sssd
    state: restarted
  when: _sssd_activatable_responders_disabled.changed
  listen: restart sssd
