---
- name: Converge
  hosts: all
  tasks:
    - name: "Include wandansible.sssd"
      ansible.builtin.include_role:
        name: "wandansible.sssd"
      vars:
        ldap_auth_host: "ldap.example.org"
        ldap_auth_port: "636"
        ldap_search_base: "dc=example,dc=org"
        ldap_filter_groups:
          - root
        ldap_config:
          id_provider: "ldap"
          auth_provider: "ldap"
          ldap_uri: "ldaps://{{ ldap_auth_host }}:{{ ldap_auth_port }}"
          ldap_id_use_start_tls: "true"
          ldap_search_base: "{{ ldap_search_base }}"
          ldap_tls_reqcert: "demand"
          ldap_tls_cacert: "/etc/ssl/ldap/cacert.pem"
          cache_credentials: "true"
          enumerate: "true"
          sudo_provider: "none"
        sssd_config:
          sssd:
            config_file_version: "2"
            domains: "LDAP"
            services:
              - "nss"
              - "pam"
              - "sudo"
              - "ssh"
          nss:
            filter_users: "root"
            filter_groups: "{{ ldap_filter_groups | join(', ') }}"
          domain/LDAP: "{{ ldap_config }}"
